# Global settings
worker_processes auto;

# Log and process settings
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

# Connection processing
events {
    worker_connections 1024;
}

# HTTP server configuration
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    # Logging
    access_log /var/log/nginx/access.log;
    
    # Performance settings
    sendfile on;
    keepalive_timeout 500;
    
    # HTTP server - just for redirection
    server {
        listen 80;
        server_name localhost euphonicintelligence.com www.euphonicintelligence.com;

        # Serve ACME challenge files for Certbot
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
    
    # HTTPS server - with SSL and proxying
    # server {
    #     listen 443 ssl;
    #     server_name localhost euphonicintelligence.com www.euphonicintelligence.com;
        
    #     ssl_certificate /etc/letsencrypt/live/euphonicintelligence.com/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/euphonicintelligence.com/privkey.pem;
        
    #     # SSL configurations
    #     ssl_protocols TLSv1.2 TLSv1.3;
    #     ssl_prefer_server_ciphers on;
    #     ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
        
    #     # Static file handling
    #     location /static/ {
    #         alias /app/staticfiles/;
    #         expires 30d;
    #         add_header Cache-Control "public, max-age=2592000";
    #     }
        
    #     # Proxy requests to Gunicorn
    #     location / {
    #         proxy_pass http://web:8000;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #         proxy_set_header X-Forwarded-Host $host;
    #         proxy_set_header X-Forwarded-Port $server_port;
            
    #         # Proxy connection settings
    #         proxy_connect_timeout 500s;
    #         proxy_read_timeout 1000s;
            
    #         # Security headers
    #         add_header X-Content-Type-Options "nosniff";
    #         add_header X-Frame-Options "SAMEORIGIN";
    #         add_header X-XSS-Protection "1; mode=block";
    #         add_header Referrer-Policy "strict-origin-when-cross-origin";
    #         add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' *.scdn.co; connect-src 'self'";
    #         add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    #         add_header Permissions-Policy "camera=(), microphone=(), geolocation=()";
    #     }
    # }
}